import { loadCourses } from '../courseLoader';
import fallCourseList from '../fallCourseList.csv?raw';

const courseMap = loadCourses(fallCourseList);

export const subjectOptions = [
  { value: 'ACC', label: 'Accounting (ACC)' },
  { value: 'ACT', label: 'Actuarial Mathematics (ACT)' },
  { value: 'ABIZ', label: 'Agribusiness and Agricultural Economics (ABIZ)' },
  { value: 'AGRI', label: 'Agriculture (AGRI)' },
  { value: 'DAGR', label: 'Agriculture Diploma (DAGR)' },
  { value: 'AGEC', label: 'Agroecology (AGEC)' },
  { value: 'ASLL', label: 'American Sign Language (ASLL)' },
  { value: 'ANSC', label: 'Animal Science (ANSC)' },
  { value: 'ANTH', label: 'Anthropology (ANTH)' },
  { value: 'ARA', label: 'Arabic (ARA)' },
  { value: 'ARTS', label: 'Arts Interdisciplinary (ARTS)' },
  { value: 'ASIA', label: 'Asian Studies (ASIA)' },
  { value: 'ASTR', label: 'Astronomy (ASTR)' },
  { value: 'BGEN', label: 'Biochem and Medical Genetics (BGEN)' },
  { value: 'BIOL', label: 'Biological Sciences (BIOL)' },
  { value: 'BIOE', label: 'Biosystems Engineering (BIOE)' },
  { value: 'BTEC', label: 'Biotechnology (BTEC)' },
  { value: 'CDN', label: 'Canadian Studies (CDN)' },
  { value: 'CATH', label: 'Catholic Studies (CATH)' },
  { value: 'CHEM', label: 'Chemistry (CHEM)' },
  { value: 'CIVIL', label: 'Civil Engineering (CIVL)' },
  { value: 'CLAS', label: 'Classical Studies (CLAS)' },
  { value: 'COMP', label: 'Computer Science (COMP)' },
  { value: 'DATA', label: 'Data Science (DATA)' },
  { value: 'DDSS', label: 'Dental Diagnostic and Surgical (DDSS)' },
  { value: 'HYGN', label: 'Dental Hygiene (HYGN)' },
  { value: 'DENT', label: 'Dentistry (DENT)' },
  { value: 'ECON', label: 'Economics (ECON)' },
  { value: 'EDUA', label: 'Education Admin, Fndns & Psych (EDUA)' },
  { value: 'EDUB', label: 'Education Curric, Tchg, & Lrng (EDUB)' },
  { value: 'ECE', label: 'Electr. and Computer Engin. (ECE)' },
  { value: 'ENG', label: 'Engineering (ENG)' },
  { value: 'ENGL', label: 'English (ENGL)' },
  { value: 'ENTM', label: 'Entomology (ENTM)' },
  { value: 'ENTR', label: 'Entrepreneurship/Small Bus. (ENTR)' },
  { value: 'EVLU', label: 'Envir. Design Landsc & Urban (EVLU)' },
  { value: 'ENVR', label: 'Environment (ENVR)' },
  { value: 'EER', label: 'Environment, Earth & Resources (EER)' },
  { value: 'EVAR', label: 'Environmental Architecture (EVAR)' },
  { value: 'EVDS', label: 'Environmental Design (EVDS)' },
  { value: 'EVIE', label: 'Environmental Interior Environ (EVIE)' },
  { value: 'FMLY', label: 'Family Social Sciences (FMLY)' },
  { value: 'FILM', label: 'Film Studies (FILM)' },
  { value: 'FIN', label: 'Finance (FIN)' },
  { value: 'FAAH', label: 'Fine Art, Art History Courses (FAAH)' },
  { value: 'FA', label: 'Fine Art, General Courses (FA)' },
  { value: 'STDO', label: 'Fine Art, Studio Courses (STDO)' },
  { value: 'FOOD', label: 'Food Science (FOOD)' },
  { value: 'FREN', label: 'French (FREN)' },
  { value: 'FSIE', label: 'French, Spanish, Italian in English (FSIE)' },
  { value: 'GMGT', label: 'General Management (GMGT)' },
  { value: 'GEOG', label: 'Geography (GEOG)' },
  { value: 'GEOL', label: 'Geological Sciences (GEOL)' },
  { value: 'GRMN', label: 'German (GRMN)' },
  { value: 'GPE', label: 'Global Political Economy (GPE)' },
  { value: 'GRK', label: 'Greek (GRK)' },
  { value: 'HEAL', label: 'Health Studies (HEAL)' },
  { value: 'HEB', label: 'Hebrew (HEB)' },
  { value: 'HIST', label: 'History (HIST)' },
  { value: 'ANAT', label: 'Human Anat. and Cell Science (ANAT)' },
  { value: 'HNSC', label: 'Human Nutritional Sciences (HNSC)' },
  { value: 'HRIR', label: 'Human Res. Mgmt/Indus Relat. (HRIR)' },
  { value: 'HUNG', label: 'Hungarian (HUNG)' },
  { value: 'ICEL', label: 'Icelandic (ICEL)' },
  { value: 'IMMU', label: 'Immunology (IMMU)' },
  { value: 'INDG', label: 'Indigenous Studies (INDG)' },
  { value: 'IDM', label: 'Interdisciplinary Management (IDM)' },
  { value: 'ITLN', label: 'Italian (ITLN)' },
  { value: 'JUD', label: 'Judaic Civilization (JUD)' },
  { value: 'KPER', label: 'Kinesio, Phys Ed, & Recreation (KPER)' },
  { value: 'KIN', label: 'Kinesiology (KIN)' },
  { value: 'LABR', label: 'Labour Studies (LABR)' },
  { value: 'LATN', label: 'Latin (LATN)' },
  { value: 'LAW', label: 'Law (LAW)' },
  { value: 'LEAD', label: 'Leadership (LEAD)' },
  { value: 'LING', label: 'Linguistics (LING)' },
  { value: 'MIS', label: 'Management Info. Systems (MIS)' },
  { value: 'MSCI', label: 'Management Science (MSCI)' },
  { value: 'MKT', label: 'Marketing (MKT)' },
  { value: 'MATH', label: 'Mathematics (MATH)' },
  { value: 'MECH', label: 'Mechanical Engineering (MECH)' },
  { value: 'MBIO', label: 'Microbiology (MBIO)' },
  { value: 'MDFY', label: 'Midwifery (MDFY)' },
  { value: 'MUSC', label: 'Music (MUSC)' },
  { value: 'NURS', label: 'Nursing (NURS)' },
  { value: 'OT', label: 'Occupational Therapy (OT)' },
  { value: 'OPM', label: 'Operations Management (OPM)' },
  { value: 'ORLB', label: 'Oral Biology (ORLB)' },
  { value: 'PHMD', label: 'Pharm. D (PHMD)' },
  { value: 'PHAC', label: 'Pharmacology (PHAC)' },
  { value: 'PHIL', label: 'Philosophy (PHIL)' },
  { value: 'PHED', label: 'Physical Education (PHED)' },
  { value: 'PHYS', label: 'Physics (PHYS)' },
  { value: 'PHGY', label: 'Physiology (PHGY)' },
  { value: 'PLNT', label: 'Plant Science (PLNT)' },
  { value: 'POL', label: 'Polish (Slavic Studies) (POL)' },
  { value: 'POLS', label: 'Political Science (POLS)' },
  { value: 'PORT', label: 'Portuguese (PORT)' },
  { value: 'PDSD', label: 'Preventive Dental Science (PDSD)' },
  { value: 'PSYC', label: 'Psychology (PSYC)' },
  { value: 'REC', label: 'Recreation Studies (REC)' },
  { value: 'REHB', label: 'Rehabilitation Sciences (REHB)' },
  { value: 'RLGN', label: 'Religion (RLGN)' },
  { value: 'RESP', label: 'Respiratory Therapy (RESP)' },
  { value: 'RSTD', label: 'Restorative Dentistry (RSTD)' },
  { value: 'RUSN', label: 'Russian (Slavic Studies) (RUSN)' },
  { value: 'SCI', label: 'Science Interdisciplinary (SCI)' },
  { value: 'SLAV', label: 'Slavic Studies (Pol,Rusn,Ukrn) (SLAV)' },
  { value: 'SWRK', label: 'Social Work (SWRK)' },
  { value: 'SOC', label: 'Sociology (SOC)' },
  { value: 'SOIL', label: 'Soil Science (SOIL)' },
  { value: 'SPAN', label: 'Spanish (SPAN)' },
  { value: 'STAT', label: 'Statistics (STAT)' },
  { value: 'SGMT', label: 'Strategy and Global Management (SGMT)' },
  { value: 'SCM', label: 'Supply Chain Management (SCM)' },
  { value: 'THTR', label: 'Theatre (THTR)' },
  { value: 'UKRN', label: 'Ukrainian (Slavic Studies) (UKRN)' },
  { value: 'UCHS', label: 'Ukrainian Cdn Heritage Studies (UCHS)' },
  { value: 'WOMN', label: 'Womens and Gender Studies (WOMN)' },
  { value: 'YDSH', label: 'Yiddish (YDSH)' }
]

export const courseOptions = {
  "ACC": generateCourseOptions("ACC"),
  "ACT": generateCourseOptions("ACT"),
  "ABIZ": generateCourseOptions("ABIZ"),
  "AGRI": generateCourseOptions("AGRI"),
  "DAGR": generateCourseOptions("DAGR"),
  "AGEC": generateCourseOptions("AGEC"),
  "ASLL": generateCourseOptions("ASLL"),
  "ANSC": generateCourseOptions("ANSC"),
  "ANTH": generateCourseOptions("ANTH"),
  "ARA": generateCourseOptions("ARA"),
  "ARTS": generateCourseOptions("ARTS"),
  "ASIA": generateCourseOptions("ASIA"),
  "ASTR": generateCourseOptions("ASTR"),
  "BGEN": generateCourseOptions("BGEN"),
  "BIOL": generateCourseOptions("BIOL"),
  "BIOE": generateCourseOptions("BIOE"),
  "BTEC": generateCourseOptions("BTEC"),
  "CDN": generateCourseOptions("CDN"),
  "CATH": generateCourseOptions("CATH"),
  "CHEM": generateCourseOptions("CHEM"),
  "CIVIL": generateCourseOptions("CIVIL"),
  "CLAS": generateCourseOptions("CLAS"),
  "COMP": generateCourseOptions("COMP"),
  "DATA": generateCourseOptions("DATA"),
  "DDSS": generateCourseOptions("DDSS"),
  "HYGN": generateCourseOptions("HYGN"),
  "DENT": generateCourseOptions("DENT"),
  "ECON": generateCourseOptions("ECON"),
  "EDUA": generateCourseOptions("EDUA"),
  "EDUB": generateCourseOptions("EDUB"),
  "ECE": generateCourseOptions("ECE"),
  "ENG": generateCourseOptions("ENG"),
  "ENGL": generateCourseOptions("ENGL"),
  "ENTM": generateCourseOptions("ENTM"),
  "ENTR": generateCourseOptions("ENTR"),
  "EVLU": generateCourseOptions("EVLU"),
  "ENVR": generateCourseOptions("ENVR"),
  "EER": generateCourseOptions("EER"),
  "EVAR": generateCourseOptions("EVAR"),
  "EVDS": generateCourseOptions("EVDS"),
  "EVIE": generateCourseOptions("EVIE"),
  "FMLY": generateCourseOptions("FMLY"),
  "FILM": generateCourseOptions("FILM"),
  "FIN": generateCourseOptions("FIN"),
  "FAAH": generateCourseOptions("FAAH"),
  "FA": generateCourseOptions("FA"),
  "STDO": generateCourseOptions("STDO"),
  "FOOD": generateCourseOptions("FOOD"),
  "FREN": generateCourseOptions("FREN"),
  "FSIE": generateCourseOptions("FSIE"),
  "GMGT": generateCourseOptions("GMGT"),
  "GEOG": generateCourseOptions("GEOG"),
  "GEOL": generateCourseOptions("GEOL"),
  "GRMN": generateCourseOptions("GRMN"),
  "GPE": generateCourseOptions("GPE"),
  "GRK": generateCourseOptions("GRK"),
  "HEAL": generateCourseOptions("HEAL"),
  "HEB": generateCourseOptions("HEB"),
  "HIST": generateCourseOptions("HIST"),
  "ANAT": generateCourseOptions("ANAT"),
  "HNSC": generateCourseOptions("HNSC"),
  "HRIR": generateCourseOptions("HRIR"),
  "HUNG": generateCourseOptions("HUNG"),
  "ICEL": generateCourseOptions("ICEL"),
  "IMMU": generateCourseOptions("IMMU"),
  "INDG": generateCourseOptions("INDG"),
  "IDM": generateCourseOptions("IDM"),
  "ITLN": generateCourseOptions("ITLN"),
  "JUD": generateCourseOptions("JUD"),
  "KPER": generateCourseOptions("KPER"),
  "KIN": generateCourseOptions("KIN"),
  "LABR": generateCourseOptions("LABR"),
  "LATN": generateCourseOptions("LATN"),
  "LAW": generateCourseOptions("LAW"),
  "LEAD": generateCourseOptions("LEAD"),
  "LING": generateCourseOptions("LING"),
  "MIS": generateCourseOptions("MIS"),
  "MSCI": generateCourseOptions("MSCI"),
  "MKT": generateCourseOptions("MKT"),
  "MATH": generateCourseOptions("MATH"),
  "MECH": generateCourseOptions("MECH"),
  "MBIO": generateCourseOptions("MBIO"),
  "MDFY": generateCourseOptions("MDFY"),
  "MUSC": generateCourseOptions("MUSC"),
  "NURS": generateCourseOptions("NURS"),
  "OT": generateCourseOptions("OT"),
  "OPM": generateCourseOptions("OPM"),
  "ORLB": generateCourseOptions("ORLB"),
  "PHMD": generateCourseOptions("PHMD"),
  "PHAC": generateCourseOptions("PHAC"),
  "PHIL": generateCourseOptions("PHIL"),
  "PHED": generateCourseOptions("PHED"),
  "PHYS": generateCourseOptions("PHYS"),
  "PHGY": generateCourseOptions("PHGY"),
  "PLNT": generateCourseOptions("PLNT"),
  "POL": generateCourseOptions("POL"),
  "POLS": generateCourseOptions("POLS"),
  "PORT": generateCourseOptions("PORT"),
  "PDSD": generateCourseOptions("PDSD"),
  "PSYC": generateCourseOptions("PSYC"),
  "REC": generateCourseOptions("REC"),
  "REHB": generateCourseOptions("REHB"),
  "RLGN": generateCourseOptions("RLGN"),
  "RESP": generateCourseOptions("RESP"),
  "RSTD": generateCourseOptions("RSTD"),
  "RUSN": generateCourseOptions("RUSN"),
  "SCI": generateCourseOptions("SCI"),
  "SLAV": generateCourseOptions("SLAV"),
  "SWRK": generateCourseOptions("SWRK"),
  "SOC": generateCourseOptions("SOC"),
  "SOIL": generateCourseOptions("SOIL"),
  "SPAN": generateCourseOptions("SPAN"),
  "STAT": generateCourseOptions("STAT"),
  "SGMT": generateCourseOptions("SGMT"),
  "SCM": generateCourseOptions("SCM"),
  "THTR": generateCourseOptions("THTR"),
  "UKRN": generateCourseOptions("UKRN"),
  "UCHS": generateCourseOptions("UCHS"),
  "WOMN": generateCourseOptions("WOMN"),
  "YDSH": generateCourseOptions("YDSH"),
}


function generateCourseOptions(title) {
    title : Array.from(courseMap.entries())
    .filter(([courseName]) => courseName.startsWith(title))
    .map(([courseName, course]) => ({
      value: courseName,
      label: `${ courseName } - ${ course.title } `
    }))
  }
